# syntax=docker/dockerfile:1

# Shared runtime image for the web service and all Bun worker services. Railway
# overrides the process command per service; keeping one image prevents the
# worker services from drifting from the web service's dependency set.
FROM oven/bun:1.3.14

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --ignore-scripts

COPY . .

ARG OUTPAY_SECRET_KEY
ARG OUTPAY_TEST_SECRET_KEY
ARG OUTPAY_LIVE_SECRET_KEY
ARG OUTPAY_PUBLIC_KEY
ARG OUTPAY_WEBHOOK_SIGNING_SECRET
ARG DATABASE_URL
ARG DATABASE_PUBLIC_URL
ARG PGDATA
ARG PGDATABASE
ARG PGHOST
ARG PGPASSWORD
ARG PGPORT
ARG PGUSER
ARG OUTPAY_DATABASE_POOL_MAX
ARG OUTPAY_AUTH_POOL_MAX
ARG POSTGRES_DB
ARG POSTGRES_PASSWORD
ARG POSTGRES_USER
ARG RAILWAY_DEPLOYMENT_DRAINING_SECONDS
ARG SSL_CERT_DAYS
ARG APP_BASE_URL
ARG BETTER_AUTH_URL
ARG OUTPAY_CHECKOUT_TTL_SECONDS
ARG OUTPAY_CHECKOUT_DETECTED_GRACE_SECONDS
ARG RESEND_API_KEY
ARG OUTPAY_EMAIL_FROM
ARG OUTPAY_EMAIL_REPLY_TO
ARG ALCHEMY_BASE_RPC_URL
ARG ALCHEMY_WEBHOOK_SIGNING_KEY
ARG ALCHEMY_NOTIFY_WEBHOOK_ID
ARG ALCHEMY_NOTIFY_API_BASE_URL
ARG CHAINSTACK_BASE_RPC_URL
ARG REDIS_URL
ARG API_RATE_LIMIT_PER_MINUTE
ARG CHECKOUT_STATUS_RATE_LIMIT_PER_MINUTE
ARG MERCHANT_WEBHOOK_SECRET_ENCRYPTION_KEY
ARG OUTPAY_USDC_SLIGHT_OVERPAY_TOLERANCE
ARG OUTPAY_ALERT_WEBHOOK_URL
ARG OUTPAY_LOG_LEVEL
ARG RPC_PRIMARY_PROVIDER
ARG RPC_SECONDARY_PROVIDER
ARG RPC_TIMEOUT_MS
ARG RPC_FAILOVER_ENABLED
ARG RPC_HEALTH_CHECK_INTERVAL_SECONDS
ARG BETTER_AUTH_SECRET
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_ENDPOINT_URL_S3
ARG AWS_ENDPOINT_URL_IAM
ARG AWS_REGION
ARG TIGRIS_BUCKET_NAME
ENV OUTPAY_SECRET_KEY=${OUTPAY_SECRET_KEY}
ENV OUTPAY_TEST_SECRET_KEY=${OUTPAY_TEST_SECRET_KEY}
ENV OUTPAY_LIVE_SECRET_KEY=${OUTPAY_LIVE_SECRET_KEY}
ENV OUTPAY_PUBLIC_KEY=${OUTPAY_PUBLIC_KEY}
ENV OUTPAY_WEBHOOK_SIGNING_SECRET=${OUTPAY_WEBHOOK_SIGNING_SECRET}
ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_PUBLIC_URL=${DATABASE_PUBLIC_URL}
ENV PGDATA=${PGDATA}
ENV PGDATABASE=${PGDATABASE}
ENV PGHOST=${PGHOST}
ENV PGPASSWORD=${PGPASSWORD}
ENV PGPORT=${PGPORT}
ENV PGUSER=${PGUSER}
ENV OUTPAY_DATABASE_POOL_MAX=${OUTPAY_DATABASE_POOL_MAX}
ENV OUTPAY_AUTH_POOL_MAX=${OUTPAY_AUTH_POOL_MAX}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV RAILWAY_DEPLOYMENT_DRAINING_SECONDS=${RAILWAY_DEPLOYMENT_DRAINING_SECONDS}
ENV SSL_CERT_DAYS=${SSL_CERT_DAYS}
ENV APP_BASE_URL=${APP_BASE_URL}
ENV BETTER_AUTH_URL=${BETTER_AUTH_URL}
ENV OUTPAY_CHECKOUT_TTL_SECONDS=${OUTPAY_CHECKOUT_TTL_SECONDS}
ENV OUTPAY_CHECKOUT_DETECTED_GRACE_SECONDS=${OUTPAY_CHECKOUT_DETECTED_GRACE_SECONDS}
ENV RESEND_API_KEY=${RESEND_API_KEY}
ENV OUTPAY_EMAIL_FROM=${OUTPAY_EMAIL_FROM}
ENV OUTPAY_EMAIL_REPLY_TO=${OUTPAY_EMAIL_REPLY_TO}
ENV ALCHEMY_BASE_RPC_URL=${ALCHEMY_BASE_RPC_URL}
ENV ALCHEMY_WEBHOOK_SIGNING_KEY=${ALCHEMY_WEBHOOK_SIGNING_KEY}
ENV ALCHEMY_NOTIFY_WEBHOOK_ID=${ALCHEMY_NOTIFY_WEBHOOK_ID}
ENV ALCHEMY_NOTIFY_API_BASE_URL=${ALCHEMY_NOTIFY_API_BASE_URL}
ENV CHAINSTACK_BASE_RPC_URL=${CHAINSTACK_BASE_RPC_URL}
ENV REDIS_URL=${REDIS_URL}
ENV API_RATE_LIMIT_PER_MINUTE=${API_RATE_LIMIT_PER_MINUTE}
ENV CHECKOUT_STATUS_RATE_LIMIT_PER_MINUTE=${CHECKOUT_STATUS_RATE_LIMIT_PER_MINUTE}
ENV MERCHANT_WEBHOOK_SECRET_ENCRYPTION_KEY=${MERCHANT_WEBHOOK_SECRET_ENCRYPTION_KEY}
ENV OUTPAY_USDC_SLIGHT_OVERPAY_TOLERANCE=${OUTPAY_USDC_SLIGHT_OVERPAY_TOLERANCE}
ENV OUTPAY_ALERT_WEBHOOK_URL=${OUTPAY_ALERT_WEBHOOK_URL}
ENV OUTPAY_LOG_LEVEL=${OUTPAY_LOG_LEVEL}
ENV RPC_PRIMARY_PROVIDER=${RPC_PRIMARY_PROVIDER}
ENV RPC_SECONDARY_PROVIDER=${RPC_SECONDARY_PROVIDER}
ENV RPC_TIMEOUT_MS=${RPC_TIMEOUT_MS}
ENV RPC_FAILOVER_ENABLED=${RPC_FAILOVER_ENABLED}
ENV RPC_HEALTH_CHECK_INTERVAL_SECONDS=${RPC_HEALTH_CHECK_INTERVAL_SECONDS}
ENV BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_ENDPOINT_URL_S3=${AWS_ENDPOINT_URL_S3}
ENV AWS_ENDPOINT_URL_IAM=${AWS_ENDPOINT_URL_IAM}
ENV AWS_REGION=${AWS_REGION}
ENV TIGRIS_BUCKET_NAME=${TIGRIS_BUCKET_NAME}

RUN bun run build

ENV NODE_ENV=production

CMD ["bun", "run", "start"]
